apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    release: monitoring
spec:
  route:
    groupBy: ['severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'email-notifications'
  receivers:
    - name: 'email-notifications'
      emailConfigs:
        - to: 'mostafa.elkhouly97@gmail.com'
          from: 'ms.elkhouly97@gmail.com'
          smarthost: 'smtp.gmail.com:587'
          authUsername: 'ms.elkhouly97@gmail.com'
          authIdentity: 'ms.elkhouly97@gmail.com'
          authPassword:
            name: gmail-auth
            key: password
